/// ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====>  			Pour1	Pourc2	Category1						Category2							Category3    			// configure categories in ZombiesCategories.c file
																																													/// (ex : 0.80,	0.95 => 80% chance to spawn zombie in 1st categorie, 15% in 2nd categorie and 5% in 3rd categorie)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_000_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		Empty,							Empty,								Empty); 				// 0 - No Zombies (don't modify this one)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_001_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	0.90,	Stalker_Mutant_Izlome_Easy,		Stalker_Zmb_Trup,					Empty);					// 01 - CountrySide
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_010_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Dayz_Zmb,						Stalker_Zmb_Trup,					Stalker_Mutant_Izlome_Easy); 				// 10 - Small Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_020_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Boar,			Stalker_Mutant_Cat_Bayn,			Stalker_Mutant_Fresh); 				// 20 - Average Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_030_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	0.90,	Stalker_Mutant_Cat_Bayn,		Stalker_Mutant_Boar,				Stalker_Mutant_Fresh);		// 30 - Big Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_040_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Fresh,			Stalker_Mutant_Cat_Bayn,			Stalker_Mutant_Dog); 				// 40 - Buildings
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_050_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Dog,				Stalker_Mutant_Fresh,				Stalker_Mutant_Boar); 				// 50 - Industrial
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_060_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Pse_Dog,			Empty,								Empty); 				// 60 - Military (Always Focus)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_070_ZombiesCategories         = new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Stalker_Mutant_Controller,		Stalker_Mutant_Burer,				Stalker_Mutant_Krovosos_Easy);					// 70 - Test
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_071_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Tark,			Empty,								Empty); 				// 71 - Prison
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_072_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Forester,		Empty,								Empty); 				// 72 - test

ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_101_MilitaryTentesCategories  = new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Krovosos_Easy,   Stalker_Mutant_Burer,				Empty); 				// 101 - Army
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_102_CastelCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Zmb_All,				Empty,								Empty); 				// 102 - Castle
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_103_ChurchCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Stalker_Mutant_Snork,			Stalker_Zmb_Trup,					Empty); 				// 103 - Church (Quantity manage in the json)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_104_ComicoCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Krovosos,		Stalker_Mutant_Krovosos_Easy,       Empty); 				// 104 - LittlePoliceStation
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_105_DispensaryCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Rat_Wolf,		Stalker_Mutant_Pse_Dog,				Empty); 				// 105 - Dispensary
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_106_FireStationCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Stalker_Mutant_Himera,			Empty,								Empty); 				// 106 - Firestation
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_107_FisherCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Himera,			Stalker_Mutant_PGigant,				Empty); 				// 107 - Fisher
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_108_GazStationCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Tushkano,		Empty,								Empty); 				// 108 - GasStation
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_109_HolidayCampCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Zmb_Monolith,			Empty,								Empty); 				// 109 - Holiday camp
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_110_HospitalCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,  	Stalker_Mutant_Poltergeist,		Empty,								Empty); 	// 110 - Hospital
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_111_IndustrialCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_PGigant,			Empty,								Empty); 				// 111 - Industrial
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_112_TownHallCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Stalker_Mutant_Burer,			Empty,								Empty); 				// 112 - TownHall
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_113_PoliceStationCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Empty,							Empty,								Empty); 				// 113 - BigPoliceStation
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_114_PrisonCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Empty,							Empty,								Empty); 				// 114 - Prison
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_115_MilitaryBaseCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Empty,							Empty,								Empty);					// 115 - QG - Military
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_116_RiffyCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Empty,							Empty,								Empty); 				// 116 - Riffy
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_117_SchoolCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1, 	1,		Empty,							Empty,								Empty); 				// 117 - School
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_118_ShopCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty);	 				// 118 - Shop (Quantity manage in the json)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_090_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); 				// 119 - Hunters around castles

/// Data groups you can tweak to add new configurations
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_091_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); // 91 - add_here_description_you_want
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_092_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); // 92 - add_here_description_you_want 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_094_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); // 94 - add_here_description_you_want
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_095_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); // 95 - add_here_description_you_want
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_093_ZombiesCategories         = new Param5<float, float, TStringArray, TStringArray, TStringArray>    (1,		1,		Empty,							Empty,								Empty); // 93 - add_here_description_you_want
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_096_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); // 96 - add_here_description_you_want
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_097_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); 				// 97 Spooky (v1.19)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_098_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty); 				// 98 Zonta	(v1.15 update)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_099_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.75,	1,		Empty,							Empty,								Empty); 				// 99 - Toxic  (Always Focus)

